export const CATEGORY_ADD = 'CATEGORY_ADD';
export const CATEGORY_ADD_SUB = 'CATEGORY_ADD_SUB';
export const CATEGORY_EDIT = 'CATEGORY_EDIT';
export const CATEGORY_REMOVE = 'CATEGORY_ADD';
export const CATEGORY_ADD = 'CATEGORY_ADD';
export const CATEGORY_ADD = 'CATEGORY_ADD';
